### ISSUE TITLE
Need a non-JS experience

### ISSUE THREAD

**Issue by aarongustafson** [melanieceraso/munchkin-10k-final#1]
Can you give it a backend? All entries must include progressive enhancement.

**Comment by melanieceraso** [comment]
I’m not sure what you mean by “backend.”  

It does have progressive enhancement.  It will work and remains useful even without javascript and the styles turned off (you just have to do the math by yourself - directions are provided, though it’s assumed that the players also have game rules.  The dice roller is also removed).

Is this not considered progressive enhancement?

Melanie A. Ceraso
melanie.ceraso@gmail.com ★ melanieceraso.com

**Comment by aarongustafson** [comment]
This is more "graceful degradation" that PE in my view, especially given
the JavaScript notice. You could do the calculations in PHP or similar
"backend" technology and include a button in the interface. Then hide the
button or clobber the submit event with JS to take over.

**Comment by melanieceraso** [comment]
The requirements for the contest didn't insist upon using any backend technology.  Given that both of us are primarily front-end UI developers, we participated the best that we could with what we had to work with.  If that, in your view, doesn't qualify us for an entry then we at least enjoyed the spirit of the challenge.

**Comment by aarongustafson** [comment]
No worries. I can talk to some of the other organizers to get their
thoughts.

**Comment by jakele** [comment]
I can see where you are coming from aarongustafson. Thanks for taking the time to respond and work with us.
If you haven't played Munchkin I would highly recommend it. We came up with the idea at work the goal was to create an app that lets you track your combat points and the monsters level. As the table top game progresses it becomes a mess of cards getting thrown around. +1cp -10cp two monsters etc. That is what we have created. We than added in js and a dice roll. We have some plans for actually building off this into a big awesome web app with player or table tracker options. The future of that is what you see in the dice roll, funny messages etc. In short the idea is to track your points for the table top game. If you load this and thought we created a simple win lose calculator that is not what we set out todo, That is a progressive enhancement. The goal was to keep the table top game moving and fun by allowing you to keep track of your totals I understand that is very simple but the best apps get out of the way.

**Comment by aarongustafson** [comment]
I have Munchkin ;-)

I went ahead and posted it yesterday.

**Comment by melanieceraso** [comment]
I sent an email in but for some reason the font broke when it got posted.  I tried the "super secret" link to update the site but it's telling me it's not published.  Any tips?

Melanie A. Ceraso
melanie.ceraso@gmail.com ★ melanieceraso.com
